### PR TITLE
Adding a new file for Irfan

### PR DESCRIPTION
**Pull request by isayyad**
We need more of Irfan files....come on...please...

### CODE REVIEW

**Comment by lancefaul** [comment]
Thou feature is dope, sir.

**Comment by isayyad** [comment]
Thanks bro!

**Comment by lancefaul** [comment]
@isayyad just add a little more awesome to the dopeness and you can commit to master.

**Comment by isayyad** [comment]
@lancefaul awesomness added....are we good to go?

**Comment by lancefaul** [comment]
Your code has been knighted. 

Sincerely,
Sir Lancealot, the Brave.
https://notinfrontofthechildren.files.wordpress.com/2013/10/sir-lancelot.jpg

**Comment by lancefaul** [comment]
:+1:

**Pull request merged**
