### PR TITLE
Revert "Create hola2"

### PR DESCRIPTION
**Pull request by cmendez1701**
Reverts certify/gecollab#22

### CODE REVIEW

**Comment by jkschoen** [comment]
but why, it was great.

**Comment by jkschoen** [comment]
@cmendez1701 could you do something.

**Comment by jkschoen** [comment]
:+1:

**Comment by adilinusah** [comment]
keep it :100:

**Comment by Rohan-NOLA** [comment]
:+1:

**Comment by cmendez1701** [comment]
:8ball:

**Pull request merged**
