### PR TITLE
Other stuff is now better because of this new stuff

### PR DESCRIPTION
**Pull request by lancefaul**
More stuff to make other stuff better.

### CODE REVIEW

**Comment by PeterBell** [comment]
Looks pretty good to me!

**Comment by PeterBell** [comment]
Hey @lancefaul could you remove the exclamation point from the h1?

**Comment by lancefaul** [comment]
@PeterBell I don't know if I can do that. I'm a little emotionally attached to this particular exclamation point.

**Comment by PeterBell** [comment]
Pleeeeease ?

**Comment by lancefaul** [comment]
Removed my poodle :-1:

**Comment by PeterBell** [comment]
:+1: - let's :shipit:

**Pull request merged**
